/**
 * these codes are generated by self-defined template
 * @author: tju
 * @Date:Jun 26, 2012  4:15:07 PM
 */

package com.zj198.dao.hibernate;

import java.util.Calendar;
import java.util.Hashtable;
import java.util.List;
import java.util.Map;

import com.zj198.dao.SinItemDAO;
import com.zj198.model.SinItem;

public class SinItemDAOImpl extends HibernateDAO<SinItem, Integer> implements SinItemDAO {

	@SuppressWarnings("unchecked")
	@Override
	public List<SinItem> findSinItemByType(Integer typeId) {
		String hql = "from SinItem where typeId = :typeId and isAuthenticated = 1 and isCancelled = 0";
		Hashtable<String, Object> params = new Hashtable<String, Object>();
		params.put("typeId", typeId);
		return super.findByHQL(hql, params);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SinItem> findSinItemByRecentN(int n) {
		String hql= "from SinItem  where isAuthenticated = 1 and isCancelled = 0 order by issuedDate desc";
		Map<String, Object> map = this.findByHqlOfMap(hql, null, n, 1);
		return (List<SinItem>) map.get("list");
	}

	/**查询条件:1.过期日为空或大于查询时间,　2.经过审核的服务信息,　3. 没有被发布方中止的信息*/
	@Override
	public Map<String, Object> findServiceItemByAvailable(int typeId, int pageSize, int pageNo) {
		params = new Hashtable<String, Object>();
		String hql = "from SinItem where (expiredDate is null or expiredDate > :today)  and isAuthenticated = 1 and isCancelled = 0 order by issuedDate desc";
		params.put("today", Calendar.getInstance().getTime());
		if (typeId > 0) {
			hql  = hql + " and typeId = :typeId";
			params.put("typeId", typeId);
		}
		return this.findByHqlOfMap(hql, params, pageSize, pageNo);
	}
	
	public Map<String, Object> findByPublisher(int contactId, int pageSize, int pageNo) {
		String hql = "from SinItem where contactId = :contactId order by issuedDate desc";
		params = new Hashtable<String, Object>();
		params.put("contactId", contactId);
		return this.findByHqlOfMap(hql, params, pageSize, pageNo);
	}

	@Override
	public Map<String, Object> findUnauthorizedServiceInfo(int pageSize,
			int pageNo) {
		String hql = "from SinItem where isAuthenticated = 0 and isCancelled=0";
		return this.findByHqlOfMap(hql, null, pageSize, pageNo);
	}

}
