/**
 * these codes are generated by self-defined template
 * @author: tju
 * @Date:Jun 26, 2012  4:08:45 PM
 */

package com.zj198.dao;

import java.util.List;
import java.util.Map;

import com.zj198.model.SinItem;

public interface SinItemDAO extends BaseDAO<SinItem, Integer> {
	
	public List<SinItem> findSinItemByType(Integer typeId);
	/**最近发布的服务信息*/
	public List<SinItem> findSinItemByRecentN(int n);
	
	/**获取可用服务信息*/
	public Map<String, Object> findServiceItemByAvailable(int typeId, int pageSize, int pageNo);
	
	/**获取未经审核的服务信息*/
	public Map<String, Object> findUnauthorizedServiceInfo(int pageSize, int pageNo);
	
	/**按发布者查询*/
	public Map<String, Object> findByPublisher(int contactId, int pageSize, int pageNo);
}
