/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.tju.android;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int androidmarker=0x7f020000;
        public static final int ic_launcher=0x7f020001;
    }
    public static final class id {
        public static final int btnCamera=0x7f050009;
        public static final int btnConnectToServer=0x7f05000f;
        public static final int btnGetLocation=0x7f050002;
        public static final int btnGps=0x7f050008;
        public static final int btnHappy=0x7f05000d;
        public static final int btnNotifications=0x7f05000b;
        public static final int btnSad=0x7f05000e;
        public static final int btnShowLocation=0x7f050004;
        public static final int btnShowMap=0x7f050005;
        public static final int btnTcp=0x7f050006;
        public static final int btnUdp=0x7f050007;
        public static final int btnWifi=0x7f05000a;
        public static final int mapview=0x7f05000c;
        public static final int mvCurrent=0x7f050000;
        public static final int spinner=0x7f050001;
        public static final int tvLocation=0x7f050003;
    }
    public static final class layout {
        public static final int camera=0x7f030000;
        public static final int current_location_map=0x7f030001;
        public static final int gps=0x7f030002;
        public static final int main=0x7f030003;
        public static final int map=0x7f030004;
        public static final int notifications=0x7f030005;
        public static final int status_bar_notifications=0x7f030006;
        public static final int tcp=0x7f030007;
        public static final int udp=0x7f030008;
        public static final int wifi=0x7f030009;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int camera=0x7f040004;
        public static final int connectToServer=0x7f04000a;
        public static final int getLocation=0x7f040008;
        public static final int gps=0x7f040006;
        public static final int hello=0x7f040000;
        public static final int notifications=0x7f040007;
        public static final int showLocation=0x7f04000b;
        public static final int showMap=0x7f040009;
        public static final int tcp=0x7f040002;
        public static final int udp=0x7f040003;
        public static final int wifi=0x7f040005;
    }
}
