/**
 * these codes are generated by self-defined template
 * @author: tju
 * @Date:Jun 26, 2012  4:07:32 PM
 */

package com.zj198.dao;

import java.util.List;

import com.zj198.model.SinType;

public interface SinTypeDAO extends BaseDAO<SinType, Integer> {
	
}
