/**
 * these codes are generated by self-defined template
 * @author: tju
 * @Date:Jun 26, 2012  4:14:03 PM
 */

package com.zj198.dao.hibernate;

import java.util.List;

import org.hibernate.Query;

import com.zj198.dao.SinTypeDAO;
import com.zj198.model.DicUsertype;
import com.zj198.model.SinType;

public class SinTypeDAOImpl extends HibernateDAO<SinType, Integer> implements SinTypeDAO {
	@Override
	public List<SinType> findAll() {
		String hql="from SinType as model";
		Query query = this.getSession().createQuery(hql);
		return query.list();
	}

}
