Ext.define('ebs.resources.ActionConstants',{
	NEW: 'New',
	EDIT: 'Edit',
	DELETE: 'Delete',
	VIEW: 'View',
	GOTO: 'Goto',
	TODAY: 'Today',
	WEEK: 'Week',
	MONTH: 'Month',
	QUARTER: 'Quarter',
	YEAR: 'Year',
	ALL: 'All',
	CREATED: 'Created',
	CREATED_BY: 'Created By',
	EXPORT: 'Export',
	REFRESH: 'Refresh',
	THIS: 'This',
	SAVE: 'Save',
	CANCEL: 'Cancel',
	USER_CUSTOMIZE_VIEW: 'Customerize View',

	/**Main Controller Loading message**/
	LOAD_PRODUCT_LINE_1: 'Product Line Loaded Successfully',
	LOAD_PRODUCT_LINE_0: 'Failed to load product line',
	LOAD_SYSTEM_VARIABLES_1: 'System variables loaded successfully',
	LOAD_SYSTEM_VARIABLES_0: 'Failed to load system varaibels',
	LOAD_SYSTEM_PARAMETERS_1: 'System paramters loaded successfully',
	LOAD_SYSTEM_PARAMETERS_0: 'Failed to load system parameters',
	LOAD_SYSTEM_OBJECTS_1: 'Load system objects successfully',
	LOAD_SYSTEM_OBJECTS_0: 'Failed to load system objects',
	LOAD_USER_PERMISSIONS_1: 'Load user permissions successfully',
	LOAD_USER_PERMISSIONS_0: 'Failed to load user permissions',
	LOAD_SYSTEM_MENUS_1: 'Load system menus successfully',
	LOAD_SYSTEM_MENUS_0: 'Failed to load system menus',
	BUILDING_APP_FRAMEWORK: 'System is building application framework'
});
